config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users

  resources :users, only: [:edit, :show, :index, :update]
  resources :books, only: [:show, :index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'home/about' => "homes#about" , as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: { message: "Title can't be blank" }
  validates :body, presence: { message: "Body can't be blank" }, length: { maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #uniquenessはnameの値が一意であること 
  validates :name, presence: true, length: { minimum: 2, message: "is too short (minimum is 2 characters)" }
  validates :name, presence: true, length: { maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  #ActiveStroageの適用　userのプロフィール画像
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  
def get_profile_image(width, height)
  # unless~endまではprofile_imageが投稿されていない場合の記述
  unless profile_image.attached?
    # 以下をfile_pathに指定
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    # file_pathにしてしたものをopen、当該fileのname、Content-Typeを記載
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
    user_path(resource)
end

def after_sign_up_path_for(resource)
    user_path(resource)
end

# ログアウト時の引数の設定に注意
def after_sign_out_path_for(resource_or_scope)
    root_path
end

protected
# 【Rails】この記事を「devise 名前 ログイン」で調べたあなたへ贈るに要件の定義の仕方書いてある
# config/initializers/devise.rbでデフォルトのemailからnameに変更したので、emailを認証のキーにするためにここで再定義を行う

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    # 一意のidを持つbookモデルのレコードを抽出
    @book_show = Book.find(params[:id])
    # 新規投稿フォーム用インスタンス
    @book = Book.new
  end

  def index
    # 新規投稿フォーム用インスタンス
    @book = Book.new
    # メモ：下記のように、current_userを指定することで、Userモデルのcurrent_user情報を持ってこれる。
    @user = current_user
    # 投稿一覧データの取得
    @books = Book.all
  end

  def create
    # データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # use_idカラムにcurrent_user.idを代入
    @book.user_id = current_user.id
    # データをデータベースに保存するためのsaveメソッド実行
    if @book.save
    # 詳細画面へリダイレクト
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
    @user = current_user
    @books = Book.all
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    # updateはnewと異なり、既存のレコードを抽出する必要があるため、params[:id]を引数に指定する必要がある。
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
  redirect_to books_path
  end
end

 private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
 def is_matching_login_user
  @book = Book.find(params[:id])
  unless @book.user_id == current_user.id
    redirect_to books_path
  end
 end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 24日　追加
  # :authenticate_user!`は、ユーザーが認証されているかどうかを確認するためのメソッドを呼び出す。
  # メソッドは、ユーザーがログインしていない場合に、ログインページにリダイレクトする。
  before_action :authenticate_user!
  
  before_action :is_matching_login_user, only: [:edit, :update]
  
  
  def edit
    @user = User.find(params[:id])
  end
  

  def show
    @book = Book.new
    @user = User.find(params[:id])
    
  end
  
  def index
    @book = Book.new
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      # @user`は、`User`モデルのインスタンスであるため、そのインスタンスの情報を表示するための詳細ページにリダイレクトすることが一般的
      # redirect_to`メソッドのオプションとしてnotice指定されており、フラッシュメッセージを表示するために使用される。
      flash[:notice] = "You have updated user successfully."
      redirect_to @user
    else
      render :edit
    end
  end
  
  
  
   private


  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!--User info-->
<h2>User info</h2>

  <%= image_tag user.get_profile_image(100,100) %>

<table class="table">
  <tbody>
    <tr></tr>
    
    <tr> 
    <th>name</th>
    <th><%= user.name %></th>
    </tr> 

    <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<!--ここまでUser infoのinstructionまで-->



<!--ここから編集ボタン-->

<!--currentがuser(呼び出される際の変数)だったら-->
<!--linkに FontAwesomeを適用させたもの-->
<!--btn：ボタンのスタイル　btn-outline-secondary:ボタンの境界線のみが表示される、セカンダリカラーのスタイルを適用するためのクラス-->
<!--btn-block:ボタンを水平方向いっぱいに広げるやつ-->
<!--bootstrapでサイズを調整-->
<div class="row">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fa-solid fa-user-gear bg-transparent"></i>
  <% end %>
  
</div>

<!--ここまで編集ボタン-->

app/views/books/_new.html.erb
<!--form_labelを使用して作成-->
<!--新規投稿画面-->
<!--form_labelを使用して作成-->

<h2 class="mt-3">New book</h2>
<!--urlを指定している-->
<%= form_with(model: book, url: books_path) do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <!--brを使用して段落でいいのか？-->
    <br>
    <%= f.text_field :title %>
    </div>

    <div class="form-group">
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
    </div>

    <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn', style: 'background-color: #28a745; color: white' %>
    </div>

<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        

<!--エラーメッセージ-->
<div id="error_explanation">        
<% if @book.errors.any? %>
  <% if @book.errors.count == 1 %>
    <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <% else %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <% end %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

        <%= form_with model: @book do |f| %>

          <div class="form-group">
            <%= f.label :title %>
            <br>
            <%= f.text_field :title %>
          </div>

          <div class="form-group">
            <%= f.label :Opinion %>
            <br>
            <%= f.text_area :body %>
          </div>

          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>

        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>
      </div>
   </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div id="error_explanation">
<% if @book.errors.any? %>
  <% if @book.errors.count == 1 %>
    <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <% else %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <% end %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="container px-5 px-sm-0">
<div class="row">
    
  <div class="col-md-3">  
<!--User info-->
<!--部分テンプレートを適用、テンプレート保存先は_list.html.erb-->
<!--部分テンプレートは以下の記述で呼び出す、_listの_は省略可能、books/list.html.erbが通常の呼び方だが、拡張子は省略でき、同じフォルダ内から呼び出す場合はフォルダ名も省略できる-->
<%= render 'list', user: @user %>

<!--新規投稿-->
<%= render 'new', book: @book %>

  </div>
  
<!--books投稿一覧-->
<div class="col-md-8 offset-md-1">
<h1>Books</h1>

<!--tableの作成-->
<table class="table table-hover table-inverse">
  <!--thead 水平方向グループ化　ヘッダー作成-->
  <thead>
    <!--tr 行を指定-->
    <tr>
      <!--th 列を指定　ヘッダーは４列指定-->
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <!--４行目に設定　colspan="3"は左の２つを含んで３つ分包含するイメージ？　メンター質問行う。-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <!--eachメソッドで@book(Book.all)の各レコードをbookに代入し、繰り返し表示-->
  <% @books.each do |book| %>
   <tr>
    <!--投稿ユーザーのプロフィールイメージ-->
    <td>
     <%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user) %>
    </td>
    <!--Bookモデルのタイトルカラム」-->
    <td>
    <%= link_to book.title, book_path(book) %>
    </td>
    <!--Bookモデルのbodyカラム-->
    <td>
    <%= book.body %>
    </td>
   </tr>
  <%end%>
  </tbody>

</table>

 </div>
 
</div>
</div>

<!--やること-->
<!--editボタンの編集-->

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container">
<div class="row">
  
  <div class="col-md-3">
<!--User info-->
<!--@book_showのuser_idカラムを持つuserのprofile_imageを表示-->
<%= render 'list', user: @book_show.user %>

<!--新規投稿 -->
<%= render 'new', book: @book %>

  </div>

<!--bookの詳細-->
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
<table class="table">
  <tbody>
    <tr>
      <td>
      <!--image_tagで（）内の画像を表示させ、link_toでその画像をリンクにする。-->
      <%= link_to image_tag(@book_show.user.get_profile_image(100,100)), user_path(@book_show.user) %>
      <br>
      <!--profile_image下に、nameカラムの表示、userの詳細ページにリンク作成-->
      <%= link_to @book_show.user.name, user_path(@book_show.user) %>
      </td>

      <td>
      <!--抽出したbookレコードのタイトルカラム表示、同一ページにリンク-->
      <%= link_to @book_show.title, book_path(@book_show) %>
      </td>

      <td>
      <%= @book_show.body %>
      </td>

       <td>
      <!--もし、book_showの持つuser_idがcurrent_userと合致したら、if以下を実行-->
      <% if @book_show.user_id == current_user.id %>
      <%= link_to "Edit", edit_book_path(@book_show), class: "btn btn-success" %>
      <% end %>
       </td>

      <td>
      <% if @book_show.user_id == current_user.id %>
      <!--link to_ヘルパーメソッドの作る要素内で、data: { confirm: }属性を使用し、確認メッセージを表示--->
      <!--link to_は、ruby on railsで使用するHTMLのa要素を作るヘルパーメソッド-->
      <%= link_to "Destroy", book_path(@book_show), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %>
      <% end %>
      </td>
    </tr>
  </tbody>
</table>
</div>


</div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <!--px-3で水平方向にパディング設定-->
    <div class="px-3 mx-auto">
      
      <h1>Welcome to 
      <!--Font Awesomeの挿入-->
      <i class="fa-solid fa-book"></i>
      <strong>Bookers</strong>
      !!
      </h1>  
    </div>  
  </div>  
</div>

app/views/homes/top.html.erb
<!--一段段落を設ける-->
<p id="notice"></p>

<!--main全体のコンテナ-->
<div class="container">
  <!--列の挿入-->
  <div class="row">
    <!--mx-autoで中央寄せ、以下は画面幅によって１２分割のうちに占める割合を指定-->
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      
      <h1>welcome to
      <!--Font Awesomeの挿入-->
      <i class="fa-solid fa-book"></i>
      <strong>Bookers</strong>
      !! 
      </h1>

      <p>In 
      <!--Font Awesomeの挿入-->
       <i class="fa-solid fa-book"></i>
      <strong>Bookers</strong>
      ,
      </p>

      <p>you can share and exchange  your opinions , inpressions , and emotions</p>

      <p>about various books!</p> 
      
      <!--Log inボタンの実装-->
      <!--btn-wrapperは、包含するボタン要素を一括りにする-->
      <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
    　
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 " %>
      
      </div>
      
      <div class="row">
      
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block"  %>
      
      </div>
      </div>
      
    </div> 
  </div>
</div>　

<!--メモ-->
<!--ボタンが拡大しなかった原因は、linkをli要素で囲んでしまったことが考えられる。-->
<!--上記により、rowの子要素ではなく、liの小要素になってしまい、li要素の横幅にlinkが依存してしまった。-->



    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Font Awesomeの導入-->
    <script src="https://kit.fontawesome.com/871dbee36e.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <!--headerの中のnavigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--containerを作成-->
    <div class="container">
    <!--左上のbookを表示、ルートパス-->
    <a class="navbar-brand" href="/"><span>Bookers</span></a>
    <!--button`要素が作成されており、`navbar-toggler`というクラスが適用。これにより、Bootstrapのデフォルトのスタイリングや動作が適用される。-->
    <!--`type="button"`: ボタンのタイプを指定しています。
     data-toggle="collapse"`: ナビゲーションバーのコンポーネントをトグル（表示/非表示）できるようにするための属性です。
    `data-target="#navbarNavDropdown"`: トグルの対象となる要素（この場合、idが"navbarNavDropdown"の要素）を指定しています。
     aria-controls="navbarNavDropdown"`: トグルの対象となる要素のidを示す属性です。
    `aria-expanded="false"`: トグルの対象となる要素が展開されていないことを示す属性です。
    `aria-label="Toggle navigation"`: トグルボタンの目的（ナビゲーションの表示/非表示を切り替えること）を説明するテキストを指定しています。
     また、`button`要素の中には、`navbar-toggler-icon`というクラスが適用された`span`要素があります。これにより、トグルボタンのアイコンが表示されます。-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
       <!--FontAwesomeを絡めた時の書き方-->
       <!--Font Awsomeのバージョン注意-->
      <li>
        <!--`nav-link`クラス: ナビゲーションリンク（通常は`<a>`タグ）に適用されるクラスです。このクラスは、Bootstrapなどのフレームワークで定義されているものであり、ナビゲーションメニュー内のリンク要素をスタイリングするために使用される-->
        <!--`text-light`クラス: テキストの色を明るい色（通常は白色）にするためのクラス-->
        <!--railsでclassを指定するときは：-->
        <%= link_to user_path(current_user), class:"nav-link text-light" do %>
        <!--FontAwesomeの挿入-->
        <i class="fa-solid fa-house"></i>Home
        <%end%>
      </li>

      <li>
        <%= link_to users_path, class:"nav-link text-light" do %>
        <i class="fa-solid fa-users"></i>Users
        <%end%>
      </li>

      <li>
        <%= link_to books_path, class:"nav-link text-light" do %>
        <i class="fa-solid fa-book-open"></i>Books
        <%end%>
      </li>

      <li>
        <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do  %>
        <i class="fa-solid fa-right-from-bracket"></i>Log out
        <%end%>
      </li>

    <% else %>

      <li>
        <%= link_to root_path, class:"nav-link text-light" do %>
        <i class="fa-solid fa-house"></i>Home
        <%end%>
      </li>

      <li>
        <%= link_to about_path, class:"nav-link text-light" do %>
        <i class="fa-solid fa-link"></i>About
        <%end%>
      </li>

      <li>
        <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
        <i class="fa-solid fa-user-plus"></i>Sign up
        <%end%>
      </li>

      <li>
        <%= link_to new_user_session_path, class:"nav-link text-light" do %>
        <i class="fa-solid fa-right-to-bracket"></i>Log in
        <%end%>
      </li>

    <% end %>
    </ul>
    </div>
    </div>
    </nav>
  </header>

  <main>
  <!--devise`と`bootstrap`が導入されている場合、`devise`はユーザー認証に関連するアクション（例：ログイン、ログアウト）を処理し、必要なフラッシュメッセージを自動的に設定します。そして、`bootstrap`はそれらのフラッシュメッセージをスタイリングして表示します。-->
  <% if flash[:notice] %>
  <%= flash[:notice] %>
  <% elsif flash[:error] %>
  <%= flash[:error] %>


  <% end %>

    <%= yield %>
  </main>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <!--rowの中で中央揃え-->
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
      <!--User info-->
      <h2>User info</h2>
      
      <div id="error_explanation">
      <% if @user.errors.any? %>
      <h3>1 error prohibited this obj from being saved:</h3>
      <ul>
      <li>Name is too short (minimum is 2 characters)</li>
      </ul>
      <% end %>
      </div>
      
      <!--form_with`メソッドは`@user`オブジェクトのクラスに基づいて、`edit`アクションである場合は`update`アクションを呼び出すURLを自動的に生成-->
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <br>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image %>
          <br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <br>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
 <div class="container px-5 px-sm-0">
<div class="row">
  
<div class="col-md-3">
<!--User info-->
<%= render 'books/list', user: current_user %>

<!--新規投稿画面-->
<%= render 'books/new', book: @book %>
<!--<div class="col-md-3">の/div-->
</div>

<!--user一覧画面-->
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
          <!--多分画像はメソッドから呼び出したほうがいい-->
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--<div class="col-md-8 offset-md-1">の/div-->
</div>

<!--<div class="row">の/div-->
</div>

<!--<div class="container px-5 px-sm-0">の/div-->
</div>

app/views/users/show.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      
<!--User info-->
<%= render 'books/list', user: @user %>

<!--新規投稿画面-->
<%= render 'books/new', book: @book %>

    <!--<div class="col-md-3">の/div-->
    </div>
    

<!--特定のユーザーの投稿一覧-->

<div class="col-md-8 offset-md-1">
  
   <h2>Books</h2>
  <table class="table table-hover table-inverse">
    
  <thead>
    
    <tr>
      
      <th></th>
      
      <th>Title</th>
      
      <th>Opinion</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    　<!--N対１の関係性のため、booksで指定する？-->
     <% @user.books.each do |book| %>
      <tr>
        <td><%= link_to image_tag(@user.get_profile_image(100, 100)), user_path(@user) %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<!--<div class="row">-->
</div>

<!--<div class="container px-5 px-sm-0">-->
</div>

 